version: "3.9"

services:
  kali:
    image: kalilinux/kali-rolling:latest
    container_name: sparx-kali_v0.1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TERM=xterm-256color
      - USER=sparx
    volumes:
      - /c/Users/willm/Documents/GitHub/kali-dev-container/data:/data
      - /c/Users/willm/Documents/GitHub/kali-dev-container/config:/home/sparx/config
    working_dir: /data
    tty: true
    stdin_open: true
