alias ll='ls -la': List files with detailed information, including hidden files.
alias la='ls -A': List all files, excluding '.' and '..'.
alias l='ls -CF': List files in a columnar format.
alias ..='cd ..': Move up one directory.
alias ...='cd ../..': Move up two directories.
alias grep='grep --color=auto': Enable color in grep search results.
alias c='clear': Clear the terminal screen.
alias h='history': Show command history.
alias rm='rm -i': Prompt before removing files.
alias cp='cp -i': Prompt before overwriting files when copying.
alias mv='mv -i': Prompt before overwriting files when moving/renaming.
alias df='df -H': Display disk usage in human-readable format.
alias du='du -ch': Display directory space usage in human-readable format.
alias mkdir='mkdir -pv': Create directories and display created directories.
alias cls='clear;ls': Clear the terminal and list files.
alias update='sudo apt-get update && sudo apt-get upgrade': Update and upgrade packages.
* alias msfconsole='sudo msfconsole': Start Metasploit Framework console.
* alias nmap='sudo nmap': Run Nmap with sudo privileges.
* alias sqlmap='sudo sqlmap': Run SQLMap with sudo privileges.
* alias nikto='sudo nikto': Run Nikto with sudo privileges.
* alias gobuster='sudo gobuster': Run GoBuster with sudo privileges.
* alias wfuzz='sudo wfuzz': Run Wfuzz with sudo privileges.
* alias ffuf='sudo ffuf': Run FFUF with sudo privileges.
* alias whatweb='sudo whatweb': Run WhatWeb with sudo privileges.
* alias searchsploit='sudo searchsploit': Search for exploits in the Exploit-DB.
* alias hydra='sudo hydra': Run Hydra with sudo privileges.
* alias john='sudo john': Run John the Ripper with sudo privileges.
* alias hashcat='sudo hashcat': Run Hashcat with sudo privileges.
* alias wpscan='sudo wpscan': Run WPScan with sudo privileges.
* alias burpsuite='sudo burpsuite': Run Burp Suite with sudo privileges (if you have it installed).
